FROM oven/bun:1.3.9-alpine AS deps
WORKDIR /app
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

FROM oven/bun:1.3.9-alpine AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

ARG DATABASE_URL
ARG BETTER_AUTH_URL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_GOOGLE_BUSINESS_NAME
ARG NEXT_PUBLIC_GOOGLE_MAPS_COORDS
ARG NEXT_PUBLIC_GOOGLE_PLACE_ID
ARG NEXT_PUBLIC_GOOGLE_PLACE_URL
ARG NEXT_PUBLIC_BUSINESS_ADDRESS
ARG NEXT_PUBLIC_BUSINESS_CITY
ARG NEXT_PUBLIC_BUSINESS_REGION
ARG NEXT_PUBLIC_FACEBOOK_URL
ARG NEXT_PUBLIC_TIKTOK_URL
ARG ADMIN_EMAIL
ARG NEXT_PUBLIC_MAINTENANCE_MODE
ARG R2_ACCOUNT_ID
ARG R2_ACCESS_KEY_ID
ARG R2_SECRET_ACCESS_KEY
ARG R2_BUCKET_NAME
ARG NEXT_PUBLIC_R2_PUBLIC_URL

ENV DATABASE_URL=$DATABASE_URL \
    BETTER_AUTH_URL=$BETTER_AUTH_URL \
    GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID \
    GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET \
    NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL \
    NEXT_PUBLIC_GOOGLE_BUSINESS_NAME=$NEXT_PUBLIC_GOOGLE_BUSINESS_NAME \
    NEXT_PUBLIC_GOOGLE_MAPS_COORDS=$NEXT_PUBLIC_GOOGLE_MAPS_COORDS \
    NEXT_PUBLIC_GOOGLE_PLACE_ID=$NEXT_PUBLIC_GOOGLE_PLACE_ID \
    NEXT_PUBLIC_GOOGLE_PLACE_URL=$NEXT_PUBLIC_GOOGLE_PLACE_URL \
    NEXT_PUBLIC_BUSINESS_ADDRESS=$NEXT_PUBLIC_BUSINESS_ADDRESS \
    NEXT_PUBLIC_BUSINESS_CITY=$NEXT_PUBLIC_BUSINESS_CITY \
    NEXT_PUBLIC_BUSINESS_REGION=$NEXT_PUBLIC_BUSINESS_REGION \
    NEXT_PUBLIC_FACEBOOK_URL=$NEXT_PUBLIC_FACEBOOK_URL \
    NEXT_PUBLIC_TIKTOK_URL=$NEXT_PUBLIC_TIKTOK_URL \
    ADMIN_EMAIL=$ADMIN_EMAIL \
    NEXT_PUBLIC_MAINTENANCE_MODE=$NEXT_PUBLIC_MAINTENANCE_MODE \
    R2_ACCOUNT_ID=$R2_ACCOUNT_ID \
    R2_ACCESS_KEY_ID=$R2_ACCESS_KEY_ID \
    R2_SECRET_ACCESS_KEY=$R2_SECRET_ACCESS_KEY \
    R2_BUCKET_NAME=$R2_BUCKET_NAME \
    NEXT_PUBLIC_R2_PUBLIC_URL=$NEXT_PUBLIC_R2_PUBLIC_URL

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN bun run build

FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

ARG DATABASE_URL
ARG BETTER_AUTH_URL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_GOOGLE_BUSINESS_NAME
ARG NEXT_PUBLIC_GOOGLE_MAPS_COORDS
ARG NEXT_PUBLIC_GOOGLE_PLACE_ID
ARG NEXT_PUBLIC_GOOGLE_PLACE_URL
ARG NEXT_PUBLIC_BUSINESS_ADDRESS
ARG NEXT_PUBLIC_BUSINESS_CITY
ARG NEXT_PUBLIC_BUSINESS_REGION
ARG NEXT_PUBLIC_FACEBOOK_URL
ARG NEXT_PUBLIC_TIKTOK_URL
ARG ADMIN_EMAIL
ARG NEXT_PUBLIC_MAINTENANCE_MODE
ARG R2_ACCOUNT_ID
ARG R2_ACCESS_KEY_ID
ARG R2_SECRET_ACCESS_KEY
ARG R2_BUCKET_NAME
ARG NEXT_PUBLIC_R2_PUBLIC_URL

ENV DATABASE_URL=$DATABASE_URL \
    BETTER_AUTH_URL=$BETTER_AUTH_URL \
    GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID \
    GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET \
    NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL \
    NEXT_PUBLIC_GOOGLE_BUSINESS_NAME=$NEXT_PUBLIC_GOOGLE_BUSINESS_NAME \
    NEXT_PUBLIC_GOOGLE_MAPS_COORDS=$NEXT_PUBLIC_GOOGLE_MAPS_COORDS \
    NEXT_PUBLIC_GOOGLE_PLACE_ID=$NEXT_PUBLIC_GOOGLE_PLACE_ID \
    NEXT_PUBLIC_GOOGLE_PLACE_URL=$NEXT_PUBLIC_GOOGLE_PLACE_URL \
    NEXT_PUBLIC_BUSINESS_ADDRESS=$NEXT_PUBLIC_BUSINESS_ADDRESS \
    NEXT_PUBLIC_BUSINESS_CITY=$NEXT_PUBLIC_BUSINESS_CITY \
    NEXT_PUBLIC_BUSINESS_REGION=$NEXT_PUBLIC_BUSINESS_REGION \
    NEXT_PUBLIC_FACEBOOK_URL=$NEXT_PUBLIC_FACEBOOK_URL \
    NEXT_PUBLIC_TIKTOK_URL=$NEXT_PUBLIC_TIKTOK_URL \
    ADMIN_EMAIL=$ADMIN_EMAIL \
    NEXT_PUBLIC_MAINTENANCE_MODE=$NEXT_PUBLIC_MAINTENANCE_MODE \
    R2_ACCOUNT_ID=$R2_ACCOUNT_ID \
    R2_ACCESS_KEY_ID=$R2_ACCESS_KEY_ID \
    R2_SECRET_ACCESS_KEY=$R2_SECRET_ACCESS_KEY \
    R2_BUCKET_NAME=$R2_BUCKET_NAME \
    NEXT_PUBLIC_R2_PUBLIC_URL=$NEXT_PUBLIC_R2_PUBLIC_URL

RUN apk add --no-cache libc6-compat wget
RUN addgroup -S nodejs -g 1001 && adduser -S nextjs -u 1001 -G nodejs

COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD wget -q --spider http://127.0.0.1:${PORT}/ || exit 1

CMD ["node", "server.js"]
